name: 'Yor GitHub Action'
description: 'Run Yor against IaC templates as a pre-packaged GitHub Action.'
inputs:
  directory:
    description: 'directory with infrastructure code to scan'
    default: '.'
    required: false
  tag_groups:
    description: 'Run scan on all checks but a specific check identifier (comma separated)'
    required: false
  tags:
    description: 'comma delimited list of yor tags to apply'
    required: false
  skip_tags:
    description: 'comma delimited list of yor tags to not apply'
    required: false
  skip_dirs:
    description: 'comma delimited list of paths for yor to skip tagging of'
    required: false
  skip_resource_types:
    description: 'comma delimited list of resource types to skip for tagging'
    required: false
  custom_tags:
    description: 'comma delimited list of paths to external (custom) tags & tag groups plugins'
    required: false
  output_format:
    description: 'The format of the output. cli, json'
    required: false
  commit_changes:
    description: 'Choose whether the action will commit changes.'
    default: true
    required: false
  config_file:
    description: 'The path to the config file which describes more configurations such as custom tag groups'
    required: false
  version:
    description: 'The yor version. Can be `latest` or a full version like `0.1.129`'
    default: latest
    required: false
  skip_resources:
    description: 'skip resources for tagging'
    required: false
  parsers:
    description: 'IAC types to tag (default: "Terraform", "CloudFormation", "Serverless")'
    required: false
  tag_modules:
    description: 'Always tag local modules'
    default: false
    required: false

branding:
  icon: 'shield'
  color: 'purple'

runs:
  using: 'node16'
  main: 'dist/index.js'
